spring:
  datasource:
    url: jdbc:h2:mem:paymentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_versioned_data: false

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081

logging:
  level:
    com.ym.payment-service: DEBUG
    org.hibernate: DEBUG
    org.springframework.transaction: DEBUG
springdoc:
  api-docs:
    path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      operations-sorter: alpha
      tags-sorter: alpha

resilience4j:
  circuitbreaker:
    instances:
      paymentControllerCircuitBreaker:
        recordExceptions:
          - feign.FeignException.InternalServerError
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.dao.DataAccessException
        ignoreException:
          - java.lang.RuntimeException
          - java.lang.IllegalArgumentException
          - com.ym.paymentservice.interfaces.exception.PaymentNotFoundException
          - com.ym.paymentservice.interfaces.exception.IdempotencyKeyExistsException

        failureRateThreshold: 50
        slidingWindowSize: 50
        permittedNumbersOfCallsInHalfOpenState: 10
        minimumNumbersOfCalls: 10
        waitDurationInOpenState: 10s