server:
  port: 8089

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: medical-records-service-db
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    listener:
      ack-mode: manual
      observation-enabled: true
    template:
      observation-enabled: true
    consumer:
      group-id: shop-records-service-consumers
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      auto-offset-reset: latest
      enable-auto-commit: false
      properties:
        spring.json.use.type.headers: false
        spring.json.trusted.packages: "*"

kafka:
  service:
    order:
      order-creation-status-topic: order.creation.status
    delivery:
      delivery-events-topic: delivery.events
    payment:
      pay-events-topic: payment.pay.events