spring:
  datasource:
    url: jdbc:h2:mem:orderdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_versioned_data: false

  h2:
    console:
      enabled: true
      path: /h2-console
  rabbitmq:
    username: admin
    password: admin
    addresses: amqp://localhost:5672
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      ack-mode: manual
      observation-enabled: true
    template:
      observation-enabled: true
    consumer:
      group-id: order-consumers
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: false

server:
  port: 8080

logging:
  level:
    com.ym.orderservice: DEBUG
    org.hibernate: DEBUG
    org.springframework.transaction: DEBUG
springdoc:
  api-docs:
    path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      operations-sorter: alpha
      tags-sorter: alpha

resilience4j:
  retry:
    instances:
      paymentServiceRetry:
        maxAttempts: 3
        waitDuration: 500ms
        retryExceptions:
          - feign.FeignException
        ignoreExceptions:
          - java.lang.RuntimeException

  circuitbreaker:
    instances:
      paymentServiceCircuitBreaker:
        recordExceptions:
          - feign.FeignException.InternalServerError
        ignoreExceptions:
          - java.lang.RuntimeException

        failureRateThreshold: 50
        slidingWindowSize: 50
        permittedNumberOfCallsInHalfOpenState: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 10s

      orderControllerCircuitBreaker:
        recordExceptions:
          - feign.FeignException.InternalServerError
          - java.util.concurrent.TimeoutException
          - org.springframework.dao.DataAccessException
        ignoreExceptions:
          - com.ym.orderservice.application.exception.OrderNotFoundException
          - com.ym.orderservice.application.exception.CustomerNotFoundException
          - org.springframework.web.client.HttpClientErrorException
          - jakarta.validation.ValidationException
          - java.lang.IllegalArgumentException

        failureRateThreshold: 50
        slidingWindowSize: 50
        permittedNumberOfCallsInHalfOpenState: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 10s
  bulkhead:
    instances:
      paymentServiceBulkhead:
        maxConcurrentCalls: 5
        maxWaitDuration: 2s
  ratelimiter:
    instances:
      paymentServiceRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 1m
        timeoutDuration: 1s
integration:
  payment-service:
    base-url: http://localhost:8081/api/payments
rabbitmq:
  service:
    payment:
      exchange-request-name: payment-request-exchange
      queue-request-name: payment-request-queue
      queue-response-name: payment-response-queue

kafka:
  service:
    delivery:
      order-paid-topic: order.paid
      delivery-creation-topic: delivery.creation
